# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8411b264f334732f409aef5f6dc0a989b0c29b154655c21e88f76e17d3254906b016f3bf1d6e4063f123f3ceb24c33aa53d43887d2fc7f9cbc88ae39f81b558

test:
  secret_key_base: 383dfcb2b51de10d69795e88bdcac719bb1693c3a9a297f138a158357751e57fca5fd3f61fba8e3b689dac53ea4d1751c46a78126f32b560b9a59a8c1d2b04f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
